### ISSUE TITLE
Cannot use it with TypeScript

### ISSUE THREAD

**Issue by unigazer** [sindresorhus/read-chunk#18]
Tried importing it

```js
import { readChunkSync } from 'read-chunk';
```

Node throws the following error:
```
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: .../node_modules/read-chunk/index.js
require() of ES modules is not supported.
require() of .../node_modules/read-chunk/index.js from .../src/routes/general.ts is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /home/unigazer/Documents/libra/cinch-node/node_modules/read-chunk/package.json.

    at Module._extensions..js (internal/modules/cjs/loader.js:1089:13)
    at Object.nodeDevHook [as .js] (/home/unigazer/Documents/libra/cinch-node/node_modules/ts-node-dev/lib/hook.js:63:13)
	...
[ERROR] 16:09:50 Error: Must use import to load ES Module: .../node_modules/read-chunk/index.js
require() of ES modules is not supported.
require() of .../node_modules/read-chunk/index.js from .../src/routes/general.ts is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /home/unigazer/Documents/libra/cinch-node/node_modules/read-chunk/package.json.
```

Tried importing it asynchronously, same result.
```js
const { readChunkSync } = await import('read-chunk');
```

package.json
```json
{
    ...
    "file-type": "^16.5.3",
    "read-chunk": "^4.0.2",
    ...
    "typescript": "^4.4.3"
    ...
}
```

My whole project is written in TypeScript, only this package has issues with import.

**Comment by sindresorhus** [comment]
https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c

**Comment by unigazer** [comment]
Oh, thank you! :)

**Comment by meekr** [comment]
@unigazer I came across the same problem you described. What changes did you do to fix this?

**Comment by unigazer** [comment]
@meekr It was a long time ago and I can't really remember how I resolved this issue, but the reply @sindresorhus wrote did the trick. Just follow the instructions @sindresorhus provided in this issue, the link to the gist.
